Capstone project
Rustamxon7/Module-1-Capstone-Project pull request #2
Opened 2021-08-10 18:12 UTC by Rustamxon7

I have created this pull request to check my capstone project. 

I have completed the mobile version and desktop version. 

I have used javaScript to connect buttons to the links. 

![CapstoneProject](https://user-images.githubusercontent.com/69011963/128912658-f2061a6d-6f11-41fa-ac07-46d85ae055e7.gif)

![CapstoneProjectMobile](https://user-images.githubusercontent.com/69011963/128912181-76849736-568c-4f2d-86fc-5d2ff4d52785.gif)

2021-08-10 21:17 UTC, sinansevgi requested changes
# Changes Required :recycle: 
------

Hi @Rustamxon7 , 

Good job so far!
I really liked how you placed components on your page. It looks really professional. 
The responsiveness of the page is amazing :clap:
There are some issues that you still need to work on to go further but you are almost there!


 ## Required Changes ♻️

- [ ]  **You should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes**.  Please provide the video link in the pull request description.
The content of the video should include:
   - A description of the project.
   - A demo of the project features (different pages and different screen sizes).
   - You should also highlight some interesting piece of code or something you built that you are very proud of.
   
- [ ] The README file should contain an "Acknowledgements" section that gives appropriate credit to Cindy Shin the author of the original design, as required by the Creative Commons License.

_Please check the inline comments for my suggestions_ :arrow_down:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgibefore we r

------

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-10 21:17 UTC, sinansevgi commented on index.html
> +
For this section, you should have a JSON object that keeps all of the speakers information and you should also have a function that iterates through the speakers list and creates HTML elements dynamically. 
Please [check the project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md#project-requirements).
- [ ] The section "Featured speakers" should be created dynamically in JavaScript.
- [ ] You should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically.


Example :

List:
```javascript
{
  name: "Hasan Mamasaidov", 
  role: "Founder of \"Dekos.uz\"", 
  description: "Lorem ipsum dolor ...", 
  photo: "image_url_here"
}
```
Function:
```javascript
window.onload = () => {
  speakerList.map(speaker => {
     .... code for creating dom elements ...
  })
}

```

2021-08-10 21:17 UTC, sinansevgi commented on index.html
> +    <div class="options-menu hidden">
[Optional]
- [ ] It will be better if you convert the cursor to the pointer when the mouse hovers over the hamburger menu button. 

 | Current | Proper |
 |------------|----------|
 | ![1](https://user-images.githubusercontent.com/1642014/128936273-d6c53d2b-ad27-4811-b7df-dc7562ca9165.png) | ![Screenshot from 2021-08-11 00-15-09](https://user-images.githubusercontent.com/1642014/128936301-4dead382-7d31-45a9-aa89-a5a0c9a75bc8.png) |

2021-08-12 21:41 UTC, KabohaJeanMark requested changes
**Hi 👋🏾  @Rustamxon7,** 

Good job so far! The UI is really impressive 😎 

You have done an awesome job working on the changes from the previous reviewer.
- Add a video demo presentation where you explain your code and one thing you are proud of. ✔️ 
- Use JS DOM scripting to dynamically display the speakers reading their content and displaying the cards on the screen instead of manually in the HTML ✔️ 
- Make your cursor a better pointer when over the links for a better User Experience.

However, there are still a few changes you have to make. 


## Required Changes ♻️
Resolve the conflicts in your README.md on the pull request and please work on the other inline comments.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-12 21:41 UTC, KabohaJeanMark commented on README.md
> +[Presentation video](https://www.loom.com/share/d7473763cda64171918df056808f02bb)
Nice 👍🏾  work on adding the presentation. I checked it out and really liked how you did it and explained that extra feature you had implemented of see more or see less buttons while viewing the presenters.

2021-08-12 21:41 UTC, KabohaJeanMark commented on index.html
> +    <div class="options-menu hidden">
Nice 👍🏾 that you have worked on this feedback and are now displaying a cursor when a user mouse moves over these links

2021-08-12 21:41 UTC, KabohaJeanMark commented on newScript.js
> +    // document.querySelector('more').addEventListener('click', (num = 6));
```suggestion

```
Please remove the various instances of commented code in this file. When you check out [this article](https://www.informit.com/articles/article.aspx?p=1334908), the author of clean code explains why it is best to leave out commented code and not commit it. 
One can also endeavour instead to use git version control. That is a way of storing the previous options one's code used. With easily identifiable commit messages, this is a big help.

2021-08-12 21:41 UTC, KabohaJeanMark commented on index.html
> +          <li>Logout</li>
OPTIONAL 

- Please consider making these anchor tags for more semantic HTML.

2021-08-13 00:17 UTC, Rustamxon7 commented on README.md
> +[Presentation video](https://www.loom.com/share/d7473763cda64171918df056808f02bb)
I'm glad you like my presentation!

2021-08-13 00:19 UTC, Rustamxon7 commented on newScript.js
> +    // document.querySelector('more').addEventListener('click', (num = 6));
Thank you for mentioning that, I almost forgot!

2021-08-13 00:20 UTC, Rustamxon7 commented on index.html
> +          <li>Logout</li>
I tried as much I understood. Let me know if I did it in a correct way.

2021-08-13 03:10 UTC, hemant-soni-vst-au4 approved these changes
Hi @Rustamxon7, 

Great work on making changes as requested by the previous reviewer. 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/jkZhf5HyZkLbBzzZsn/giphy.gif)

Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 03:10 UTC, hemant-soni-vst-au4 commented on newScript.js
> +  // window.open(url, '_blank').focus();
- [Optional] Kindly try to delete the commented part from the file. It is not good practice to leave commented codes.

2021-08-28 18:42 UTC, merged